root ./www;
index index.html index.htm;
autoindex off;
client_max_body_size 10000000;
large_client_header_buffers 8192;
client_header_buffer_size 8192;
upload_store ./www/uploads;

server {
    listen 127.0.0.1:8080;
    root ./www/8080;
    
    index index.html index.htm;
    autoindex on;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    error_page 403 /error/page403.html;
   
    upload_store ./www/uploads;
    
    
    location /files/ {
        root ./www/8080/files;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:9090;
    root ./www/9090;
    
    index index.html;
    autoindex off;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    
    # return 301 http://localhost:8080/;
    
}

server {
    listen 127.0.0.1:8888;
    root ./www/8888;
    
    location / {
        limit_except GET;
        autoindex on;    
    }

    location *.bla {
        limit_except POST;
        #CGI cgi_test
    }

    location /post_body {
        root ./www/8888/post_body;
        limit_except POST;
        client_max_body_size 100;
        return 200 POST_body_received;
    }
    location /directory {
        root ./www/8888/YoupiBanane;
        index youpi.bad_extension;    
        autoindex on;        
    }


    error_page 404 /error/page404.html;
    
}
