root ./www;
index index.html index.htm;
autoindex off;
large_client_header_buffers 1000000;
client_header_buffer_size 1000000;
max_connections 1000;
session_timeout 3600;

server {
    listen 127.0.0.1:8080;
    root ./www/8080;
    
    index index.html index.htm index.php;
    upload_store ./www/8080/uploads;
    autoindex on;
    client_max_body_size 1000000;

    error_page 404 /error/page404.html;
    error_page 403 /error/page403.html;

    cgi /usr/bin/python3;
    cgi /usr/bin/php-cgi .php;
    cgi /usr/bin/cat .cat;
    cgi /usr/bin/node .js;
    cgi /usr/bin/dog .dog;
    cgi /usr/bin/ls .ls;
    cgi /usr/bin/false .false;

    location /kapouet {
        root ./www/8080/;
        # autoindex on;
    }

    location / {
        root ./www/8080/;
        autoindex on;
    }

    location /redirect {
        return 301 / ;
    }
}

server {
    listen 127.0.0.1:9090;
    root ./www/9090;
    
    index index.html;
    autoindex off;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    
    return 301 http://localhost:8080/;
    
}

server {
    listen 127.0.0.1:8888;
    root ./www/8888;
    
    client_max_body_size 200000000;

    location / {
		cgi ./cgi_tester .bla;
		root ./www/8888;
		allow_methods GET;
		autoindex on;
    }
    
    location /post_body FILE {
		allow_methods POST;
        upload_store ./www/8888/;
        client_max_body_size 100;
    }

    location /directory {
        root ./www/8888/YoupiBanane;
        index youpi.bad_extension;
		upload_store ./www/8888/YoupiBanane/;
		cgi ./cgi_tester .bla;
    }

	location /directory/Yeah {
        root ./www/8888/YoupiBanane/Yeah;
        index youpi.bad_extension;
		return 404 "lol";
	}

	location /directory/Yeah/not_happy.bad_extension {
        root ./www/8888/YoupiBanane/Yeah/;
		return 200 "lol";
        index youpi.bad_extension;
	}

}