root ./www;
index index.html index.htm;
autoindex off;
client_max_body_size 10000000;
large_client_header_buffers 8192;
client_header_buffer_size 8192;
upload_store ./www/uploads;

server {
    listen 127.0.0.1:8080;
    root ./www/8080;
    
    index index.html index.htm;
    autoindex on;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    error_page 403 /error/page403.html;
    
    limit_except GET POST DELETE {
    }
    
    upload_store ./www/uploads;
    
    location /api/ {
        root ./www/8080/api;
        autoindex off;
        client_max_body_size 5000000;
        limit_except GET POST {
        }
    }
    
    location /files/ {
        root ./www/8080/files;
        autoindex on;
        limit_except GET {
        }
    }
}

server {
    listen 127.0.0.1:9090;
    root ./www/9090;
    
    index index.html;
    autoindex off;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    
    return 301 http://localhost:8080/;
    
    limit_except GET {
    }
    
    location / {
        autoindex off;
    }
}

server {
    listen 127.0.0.1:8888;
    root ./www/8888;
    
    index index.html;
    autoindex off;
    client_max_body_size 10000000;
    
    error_page 404 /error/page404.html;
    
    limit_except GET {
    }
    
    location /api/ {
        client_max_body_size 1000000;
        limit_except GET {
        }
    }
}
