root ./www/8888;
autoindex off;
large_client_header_buffers 1000000;
client_header_buffer_size 1000000;
max_connections 1000;
session_timeout 3600;

server {
    listen 8888;

    cgi /usr/bin/python3;

    root ./www/8888;
    index index.html index.htm;
    autoindex off;
    client_max_body_size 10000000;
    allow_methods GET POST DELETE;
    error_page 404 ./404.html;

    upload_store ./www/8888/uploads;

    location /uploads/ {
        root ./www/8888/uploads;
        autoindex on;
    }

    location / {
        root ./www/8888;
        autoindex off;
    }
}