root

index

error_page

autoindex

client_max_body_size

# Serveur 1
server {
	listen 80;

	server_name 

	root

	index

	error_page

	autoindex

	client_max_body_size

	cgi_handler

	location / {

		root

		autoindex

		client_max_body_size

		index

		error_page

		cgi_handler

		limit_except

		upload_store

		return

	}

	location /www/ {
	}
}

# Serveur 2
server {
	listen 81
}

# Serveur HTTPS
server {
	listen 443;

	location /www/ {
		root
	}

	location /admin/ {
		limit_except

		upload_store

		return
	}
}
