# Erreur: accolade non fermée
root /var/www/html;

server {
	listen 8080;
	root /var/www/server;
	index index.html;
	
	location / {
		root /var/www/public;
		autoindex on;
	# Manque l'accolade fermante de location
}
