# Erreur: location dupliquée
root ./var/www/html;

server {
	listen 8080;
	root ./var/www/server;
	
	location /test/ {
		root ./var/www/test1;
		index index.html;
	}
	
	location /test/ {
		root ./var/www/test2;
		index index.htm;
	}
}
